

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_MANUAL_SIG_HANDLE=true
    env_file:
      - .env
